name: Create Tag Daily

on:
   workflow_dispatch:
 # schedule:
 #   - cron: '0 0 * * *' # Run every day at midnight

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.date.outputs.date }}
          message: "Tag created on ${{ steps.date.outputs.date }}"
            
